<?php
/** @var \App\Models\Invoice $invoice */
/** @var string|null $logoPath */
$seller = $invoice->seller_snapshot;
$buyer = $invoice->buyer_snapshot;
$money = static fn (mixed $value): string => number_format((float) $value, 2, ',', ' ') . ' ' . $invoice->currency;
$date = static fn ($value): string => $value ? $value->format('d.m.Y') : '—';
$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$rate = (float) ($seller['vat_rate'] ?? 0);
$showShipping = $invoice->type !== 'credit_note' || abs((float) $invoice->shipping_net) >= 0.01;
$hasVat = $rate > 0 && ($showShipping || array_reduce($invoice->items_snapshot, static fn (bool $hasVat, array $item): bool => $hasVat || (float) ($item['tax_rate'] ?? 0) > 0, false));
$shippingTax = $hasVat ? round((float) $invoice->shipping_net * $rate / 100, 2) : 0.0;
$shippingGross = round((float) $invoice->shipping_net + $shippingTax, 2);
$payment = (string) ($invoice->payment_snapshot['label'] ?? '—');
?>
<!doctype html><html lang="bg"><head><meta charset="utf-8"><style>
@page{margin:32px 38px}body{font-family:"DejaVu Sans",sans-serif;color:#17211a;font-size:10px;line-height:1.45}h1{font-size:23px;margin:0 0 4px}.muted{color:#65726a}.invoice-logo-wrap{text-align:center;margin:0 0 14px}.top{border-bottom:2px solid #2f7d4b;padding-bottom:16px;margin-bottom:20px}.top table,.parties,.totals{width:100%;border-collapse:collapse}.right{text-align:right}.invoice-logo{max-width:128px;max-height:56px}.badge{display:inline-block;padding:4px 8px;background:#edf7f0;color:#25643d;font-weight:bold}.parties td{width:50%;vertical-align:top;padding:13px;border:1px solid #dfe7e1}.parties td+td{border-left:0}.party-title{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#718078;margin-bottom:7px}.items{width:100%;border-collapse:collapse;margin-top:20px}.items th{background:#f2f5f3;padding:8px 6px;text-align:left;border-bottom:1px solid #cfd9d2}.items td{padding:8px 6px;border-bottom:1px solid #e5ebe7;vertical-align:top}.items .num{text-align:right;white-space:nowrap}.totals{width:48%;margin:16px 0 0 auto}.totals td{padding:4px 0}.totals .grand td{font-size:13px;font-weight:bold;border-top:2px solid #2f7d4b;padding-top:8px}.reason{margin-top:18px;padding:10px;background:#fff7e9;border-left:3px solid #c68519}.footer{position:fixed;bottom:0;left:0;right:0;color:#78837c;font-size:8px;text-align:center}
</style></head><body>
<?php if ($logoPath): ?><div class="invoice-logo-wrap"><img class="invoice-logo" src="<?= $escape($logoPath) ?>" alt="Лого"></div><?php endif; ?><div class="top"><table><tr><td><h1><?= $invoice->type === 'credit_note' ? 'Кредитно известие' : 'Фактура' ?></h1><div class="muted">№ <?= $escape($invoice->number) ?> / <?= $date($invoice->issue_date) ?></div><?php if ($invoice->parentInvoice): ?><div class="muted">към фактура № <?= $escape($invoice->parentInvoice->number) ?></div><?php endif; ?></td><td class="right"><span class="badge"><?= $invoice->status === 'cancelled' ? 'АНУЛИРАНА' : 'ОРИГИНАЛ' ?></span><div style="margin-top:8px">Поръчка #<?= $escape($invoice->order->number) ?></div><div>Начин на плащане: <?= $escape($payment) ?></div><div class="muted">Данъчно събитие: <?= $date($invoice->tax_event_date) ?></div></td></tr></table></div>
<table class="parties"><tr><td><div class="party-title">Доставчик</div><strong><?= $escape($seller['company'] ?? '') ?></strong><br>ЕИК: <?= $escape($seller['eik'] ?? '') ?><br><?php if ($hasVat && !empty($seller['vat_number'])): ?>ДДС №: <?= $escape($seller['vat_number']) ?><br><?php endif; ?><?= $escape($seller['address'] ?? '') ?><br><?php if (!empty($seller['mol'])): ?>МОЛ: <?= $escape($seller['mol']) ?><?php endif; ?></td><td><div class="party-title">Получател</div><strong><?= $escape($buyer['company'] ?? '') ?></strong><br>ЕИК: <?= $escape($buyer['eik'] ?? '') ?><br><?php if (!empty($buyer['vat_number'])): ?>ДДС №: <?= $escape($buyer['vat_number']) ?><br><?php endif; ?><?= $escape($buyer['address'] ?? '') ?><br>МОЛ: <?= $escape($buyer['mol'] ?? '') ?></td></tr></table>
<table class="items"><thead><tr><th>Описание</th><th>SKU</th><th class="num">Кол.</th><th class="num">Ед. цена</th><th class="num">Дан. основа</th><th class="num">ДДС</th><th class="num">Общо</th></tr></thead><tbody><?php foreach ($invoice->items_snapshot as $item): ?><tr><td><?= $escape($item['name']) ?></td><td><?= $escape($item['sku']) ?></td><td class="num"><?= (int) $item['qty'] ?></td><td class="num"><?= $money($item['unit_gross']) ?></td><td class="num"><?= $money($item['net_total']) ?></td><td class="num"><?= $hasVat ? $escape(number_format((float) $item['tax_rate'], 0)) . '%<br>' . $money($item['tax']) : '—' ?></td><td class="num"><strong><?= $money($item['gross_total']) ?></strong></td></tr><?php endforeach; ?><?php if ($showShipping): ?><tr><td>Доставка</td><td></td><td class="num"><?= $invoice->type === 'credit_note' ? -1 : 1 ?></td><td class="num"><?= $money($shippingGross) ?></td><td class="num"><?= $money($invoice->shipping_net) ?></td><td class="num"><?= $hasVat ? $escape(number_format($rate, 0)) . '%<br>' . $money($shippingTax) : '—' ?></td><td class="num"><strong><?= $money($shippingGross) ?></strong></td></tr><?php endif; ?></tbody></table>
<table class="totals"><?php if ($hasVat): ?><tr><td>Данъчна основа</td><td class="right"><?= $money((float)$invoice->subtotal_net + (float)$invoice->shipping_net - (float)$invoice->discount_net) ?></td></tr><?php endif; ?><tr><td>Отстъпки</td><td class="right"><?= $money($invoice->discount_net) ?></td></tr><tr><td>ДДС</td><td class="right"><?= $hasVat ? $money($invoice->tax_amount) : 'Не се начислява' ?></td></tr><tr class="grand"><td>Общо</td><td class="right"><?= $money($invoice->total_gross) ?></td></tr></table>
<?php if ($invoice->reason): ?><div class="reason"><strong>Основание:</strong> <?= $escape($invoice->reason) ?></div><?php endif; ?>
<div class="footer">Документът е генериран електронно и се пази като неизменяем архив към поръчката.</div>
</body></html>
