export const STORAGE_KEYS = {
  token: 'borz33.admin.token',
  user: 'borz33.admin.user',
  deviceUuid: 'borz33.admin.deviceUuid',
} as const;

export const routes = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  home: '/',
  orders: '/orders',
  ordersShow: '/orders/:id',
  invoices: '/invoices',
  invoicesShow: '/invoices/:id',
  products: '/products',
  productsNew: '/products/new',
  productsShow: '/products/:id',
  productsEdit: '/products/:id/edit',
  categories: '/categories',
  categoriesNew: '/categories/new',
  categoriesEdit: '/categories/:id',
  media: '/media',
  pages: '/pages',
  pagesNew: '/pages/new',
  pagesEdit: '/pages/:id',
  banners: '/banners',
  bannersNew: '/banners/new',
  bannersEdit: '/banners/:id',
  users: '/users',
  usersNew: '/users/new',
  usersEdit: '/users/:id',
  customers: '/customers',
  content: '/content',
  campaigns: '/campaigns',
  shipments: '/shipments',
  messages: '/messages',
  messagesShow: '/messages/:id',
  reports: '/reports',
  accounting: '/accounting',
  accountingGuide: '/accounting/guide',
  settings: '/settings',
} as const;
