import { useEffect,useMemo,useState,type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { Archive,BookOpen,BookOpenText,Download,Landmark,LockKeyhole,RefreshCw,RotateCcw,WalletCards } from 'lucide-react';
import { closeAccountingPeriod,createAccountingTransaction,downloadAccounting,getAccounting,getAccountingReport,reconcileEcont,type AccountingDashboard,type AccountingFilters } from '@/api/accounting';
import { routes } from '@/app/constants';
import { useAppSelector } from '@/app/hooks';
import { useGlobalLoading } from '@/components/loading-provider';
import { PageHeader } from '@/components/page-header';
import { Button } from '@/components/ui/Button';
import { Field } from '@/components/ui/Field';
import { HelpHint } from '@/components/ui/HelpHint';
import { SelectField } from '@/components/ui/SelectField';
import { formatDateTime,formatMoney } from '@/lib/format';
import { toast,toastError } from '@/lib/toast';

const now=new Date();const initial:AccountingFilters={date_from:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,date_to:new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10),order_status:'all',payment_method:'all',invoiced:'all',paid:'all'};
const reports=[['sales','Продажби'],['invoices','Фактури'],['credit_notes','Кредитни известия'],['refunds','Възстановявания'],['deliveries','Доставки / Econt'],['payments','Всички плащания'],['card','Плащания с карта'],['bank_transfer','Банков превод'],['cash_on_delivery','Наложен платеж']];
const methodLabels:Record<string,string>={card:'Карта',bank_transfer:'Банков превод',cash_on_delivery:'Наложен платеж'};
const actionLabels:Record<string,string>={'transaction.created':'Записана платежна операция','econt.reconciled':'Сверена Econt пратка','period.closed':'Приключен счетоводен период','invoice.issued':'Издадена фактура','credit_note.issued':'Издадено кредитно известие','invoice.cancelled':'Анулиран документ','order.fulfillment_changed':'Променено изпълнение на поръчка'};

export function AccountingPage(){
 const token=useAppSelector(s=>s.auth.token)??'';const [filters,setFilters]=useState(initial);const [data,setData]=useState<AccountingDashboard|null>(null);const [busy,setBusy]=useState(true);const [reportType,setReportType]=useState('sales');const [rows,setRows]=useState<Array<Record<string,unknown>>>([]);const [operation,setOperation]=useState({order_id:'',type:'payment',method:'cash_on_delivery',amount:'',occurred_at:new Date().toISOString().slice(0,16),external_reference:''});const [econt,setEcont]=useState({order_id:'',shipment_status:'sent',tracking_number:'',cod_amount:'',company_received_amount:'',received_at:''});const [closing,setClosing]=useState(initial.date_from.slice(0,7));useGlobalLoading(busy);
 const query=useMemo(()=>new URLSearchParams(filters).toString(),[filters]);
 async function load(){setBusy(true);try{const [dashboard,report]=await Promise.all([getAccounting(token,filters),getAccountingReport(token,reportType,filters)]);setData(dashboard.data);setRows(report.data.rows);}catch(e){toastError(e,'Счетоводните данни не можаха да се заредят.');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[token,query,reportType]);
 const update=(key:keyof AccountingFilters,value:string)=>setFilters(v=>({...v,[key]:value}));
 async function saveOperation(){try{await createAccountingTransaction(token,{...operation,order_id:Number(operation.order_id),amount:Number(operation.amount),occurred_at:operation.occurred_at.replace('T',' ')});toast.success('Платежната операция е записана.');setOperation(v=>({...v,amount:'',external_reference:''}));await load();}catch(e){toastError(e,'Операцията не беше записана.');}}
 async function saveEcont(){try{await reconcileEcont(token,{...econt,order_id:Number(econt.order_id),cod_amount:Number(econt.cod_amount),company_received_amount:Number(econt.company_received_amount),received_at:econt.received_at?econt.received_at.replace('T',' '):null});toast.success('Econt пратката е сверена.');await load();}catch(e){toastError(e,'Сверяването не беше записано.');}}
 async function close(){if(!window.confirm(`Периодът ${closing} ще бъде заключен. Продължавате ли?`))return;try{await closeAccountingPeriod(token,closing);toast.success('Периодът е приключен и заключен.');await load();}catch(e){toastError(e,'Периодът не можа да бъде приключен.');}}
 const headers=rows[0]?Object.keys(rows[0]):[];
 return <div className="page accounting-page"><PageHeader title="Счетоводство" help="Обединява snapshot данните от поръчки и документи с реално записаните плащания, възстановявания и Econt сверявания. Данните служат за проверка, експорт и месечно приключване." crumbs={[{label:'Табло',to:routes.home},{label:'Счетоводство'}]} actions={<><Button asChild variant="outline"><Link to={routes.accountingGuide}><BookOpenText/>Подробно ръководство</Link></Button><Button variant="outline" onClick={()=>void load()}><RefreshCw/>Обнови</Button></>}/>
 <section className="accounting-filters"><Field id="acc-from" label="От дата" help="Първият ден, включен в dashboard-а, справката и експорта. Продажбите използват дата на поръчка, документите — дата на издаване, а плащанията — дата на операцията." type="date" value={filters.date_from} onChange={e=>update('date_from',e.target.value)}/><Field id="acc-to" label="До дата" help="Последният включен ден. Изберете целия месец, когато подготвяте месечно приключване." type="date" value={filters.date_to} onChange={e=>update('date_to',e.target.value)}/><SelectField id="acc-status" label="Статус на поръчка" help="Ограничава резултатите според текущия етап на поръчката. „Всички“ не изключва отменени поръчки." value={filters.order_status} onChange={e=>update('order_status',e.target.value)}><option value="all">Всички</option><option value="pending">Чакаща</option><option value="confirmed">Потвърдена</option><option value="processing">Обработва се</option><option value="shipped">Изпратена</option><option value="delivered">Доставена</option><option value="cancelled">Отказана</option></SelectField><SelectField id="acc-method" label="Начин на плащане" help="Филтрира по метода, избран в поръчката: карта, банков превод или наложен платеж." value={filters.payment_method} onChange={e=>update('payment_method',e.target.value)}><option value="all">Всички</option>{Object.entries(methodLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</SelectField><SelectField id="acc-invoiced" label="Фактуриране" help="„Фактурирани“ са поръчки с издадена и неанулирана фактура. Полезно е за откриване на поръчки без документ." value={filters.invoiced} onChange={e=>update('invoiced',e.target.value)}><option value="all">Всички</option><option value="yes">Фактурирани</option><option value="no">Нефактурирани</option></SelectField><SelectField id="acc-paid" label="Плащане" help="Поръчката е платена, когато сборът на завършените платежни операции покрива цялата ѝ стойност." value={filters.paid} onChange={e=>update('paid',e.target.value)}><option value="all">Всички</option><option value="yes">Платени</option><option value="no">Неплатени</option></SelectField></section>
 {data?<><section className="accounting-kpis"><Metric icon={<Landmark/>} label="Оборот" help="Брутната стойност на продажбите за избора, намалена с издадените кредитни известия." value={formatMoney(data.summary.turnover)}/><Metric icon={<BookOpen/>} label="Данъчна основа" help="Стойността преди ДДС от запазените snapshots на документите или поръчките." value={formatMoney(data.summary.tax_base)}/><Metric icon={<WalletCards/>} label="Начислено ДДС" help="ДДС според ставката, запазена при поръчката или издаването на документа. При фирма без ДДС регистрация е 0,00 €." value={formatMoney(data.summary.vat)}/><Metric label="Платени поръчки" help="Поръчки, чиято стойност е покрита от завършени платежни операции." value={String(data.summary.paid_orders)}/><Metric label="Неплатени поръчки" help="Поръчки без записано пълно плащане. Самият статус „доставена“ не ги прави автоматично платени." value={String(data.summary.unpaid_orders)}/><Metric icon={<RotateCcw/>} label="Възстановени суми" help="Сборът на реално записаните завършени възстановявания. Това е отделно от стойността на кредитните известия." value={formatMoney(data.summary.refunded_amount)}/><Metric label="Кредитни известия" help="Брой и абсолютна стойност на издадените кредитни известия за избора." value={`${data.summary.credit_notes_count} · ${formatMoney(data.summary.credit_notes_amount)}`}/></section><section className="accounting-methods"><SectionTitle title="Приходи по начин на плащане" help="Сумира завършените платежни операции по реалния им метод. Данните идват от платежния журнал, а не само от избора в поръчката."/>{Object.entries(data.payment_methods).map(([m,v])=><div key={m}><span>{methodLabels[m]??m}</span><strong>{formatMoney(v)}</strong></div>)}</section></>:null}
 <section className="accounting-panel"><header><div><SectionTitle title="Справки" help="Таблицата показва избрания вид счетоводна справка. Общите филтри се прилагат и към CSV/Excel експорта."/><p>Филтрите по-горе се прилагат и към експортите.</p></div><div className="accounting-actions"><SelectField id="report-type" label="Вид справка" help="Продажби показва поръчките; документните справки използват дата на издаване; платежните справки използват дата на операцията; доставки показва Econt сверяванията." value={reportType} onChange={e=>setReportType(e.target.value)}>{reports.map(([v,l])=><option key={v} value={v}>{l}</option>)}</SelectField><Button variant="outline" title="Изтегля машинночетим CSV за текущата справка и филтри" onClick={()=>void downloadAccounting(token,`/admin/accounting/export/${reportType}/csv?${query}`,`accounting-${reportType}.csv`)}><Download/>CSV</Button><Button variant="outline" title="Изтегля Excel файл за текущата справка и филтри" onClick={()=>void downloadAccounting(token,`/admin/accounting/export/${reportType}/xlsx?${query}`,`accounting-${reportType}.xlsx`)}><Download/>Excel</Button><Button title="Създава ZIP с документи, справки и обобщение; не заключва периода" onClick={()=>void downloadAccounting(token,'/admin/accounting/package',`accounting-${filters.date_from}-${filters.date_to}.zip`,filters)}><Archive/>Счетоводен пакет</Button></div></header><div className="accounting-table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{headers.map(h=><td key={h}>{typeof row[h]==='boolean'?(row[h]?'Да':'Не'):String(row[h]??'—')}</td>)}</tr>)}</tbody></table>{rows.length===0?<p className="accounting-empty">Няма записи за избрания период и филтри.</p>:null}</div></section>
 <div className="accounting-two-col"><section className="accounting-panel"><SectionTitle title="Запиши плащане или възстановяване" help="Тук се записва реално движение на пари. Статусът на поръчката сам по себе си не създава плащане. Записите влизат в dashboard-а, справките и audit log-а."/><Field id="tx-order" label="ID на поръчка" help="Вътрешният цифров ID от адреса или детайлите на поръчката. Операцията ще бъде свързана с тази поръчка." type="number" min="1" value={operation.order_id} onChange={e=>setOperation(v=>({...v,order_id:e.target.value}))}/><div className="accounting-inline"><SelectField id="tx-type" label="Операция" help="„Плащане“ увеличава получените средства. „Възстановяване“ отбелязва реално върнати пари и не може да надвиши наличната платена сума." value={operation.type} onChange={e=>setOperation(v=>({...v,type:e.target.value}))}><option value="payment">Плащане</option><option value="refund">Възстановяване</option></SelectField><SelectField id="tx-method" label="Метод" help="Реалният канал, по който парите са постъпили или върнати. Използва се за разбивката по платежен метод." value={operation.method} onChange={e=>setOperation(v=>({...v,method:e.target.value}))}>{Object.entries(methodLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</SelectField></div><Field id="tx-amount" label="Сума (€)" help="Брутната реално платена или върната сума в евро. При частично плащане или възстановяване въведете само конкретната част." type="number" min="0.01" step="0.01" value={operation.amount} onChange={e=>setOperation(v=>({...v,amount:e.target.value}))}/><Field id="tx-date" label="Дата и час" help="Моментът на реалното плащане или възстановяване. Тази дата определя в кой период влиза платежната справка." type="datetime-local" value={operation.occurred_at} onChange={e=>setOperation(v=>({...v,occurred_at:e.target.value}))}/><Field id="tx-reference" label="Референция" help="По желание: номер на картова транзакция, банков превод, Econt отчет или друга външна следа за проверка." value={operation.external_reference} onChange={e=>setOperation(v=>({...v,external_reference:e.target.value}))}/><Button disabled={!operation.order_id||!operation.amount} onClick={()=>void saveOperation()}>Запиши операция</Button></section>
 <section className="accounting-panel"><SectionTitle title="Econt сверяване" help="Свързва поръчката с реалния статус на пратката и сравнява очаквания наложен платеж с получената от фирмата сума."/><Field id="econt-order" label="ID на поръчка" help="Поръчката, към която принадлежи товарителницата и наложеният платеж." type="number" min="1" value={econt.order_id} onChange={e=>setEcont(v=>({...v,order_id:e.target.value}))}/><SelectField id="econt-status" label="Статус" help="Реалното движение според Econt: изпратена, доставена или върната пратка." value={econt.shipment_status} onChange={e=>setEcont(v=>({...v,shipment_status:e.target.value}))}><option value="sent">Изпратена</option><option value="delivered">Доставена</option><option value="returned">Върната</option></SelectField><Field id="econt-tracking" label="Товарителница" help="Номерът от Econt, използван за проследяване и сверяване с куриерския отчет." value={econt.tracking_number} onChange={e=>setEcont(v=>({...v,tracking_number:e.target.value}))}/><div className="accounting-inline"><Field id="econt-cod" label="Наложен платеж (€)" help="Очакваната брутна сума, която Econt трябва да събере от клиента." type="number" min="0" step="0.01" value={econt.cod_amount} onChange={e=>setEcont(v=>({...v,cod_amount:e.target.value}))}/><Field id="econt-received" label="Получена сума (€)" help="Сумата, която действително е постъпила при фирмата според Econt или банковия отчет. Разликата се вижда в справката за доставки." type="number" min="0" step="0.01" value={econt.company_received_amount} onChange={e=>setEcont(v=>({...v,company_received_amount:e.target.value}))}/></div><Field id="econt-date" label="Получена на" help="Датата и часът, когато фирмата реално е получила сумата от наложения платеж." type="datetime-local" value={econt.received_at} onChange={e=>setEcont(v=>({...v,received_at:e.target.value}))}/><Button disabled={!econt.order_id} onClick={()=>void saveEcont()}>Запиши сверяване</Button></section></div>
 <div className="accounting-two-col"><section className="accounting-panel accounting-closing"><SectionTitle icon={<LockKeyhole/>} title="Месечно счетоводно приключване" help="Създава окончателно snapshot обобщение и ZIP пакет, след което заключва месеца срещу случайни финансови промени. Използвайте го само след пълно сверяване."/><p>Генерира архивен пакет и заключва месеца срещу промени по финансовите записи.</p><Field id="closing-period" label="Месец" help="Месецът, който ще бъде архивиран и заключен. Проверете предварително всички документи, плащания, възстановявания и Econt суми." type="month" value={closing} onChange={e=>setClosing(e.target.value)}/><Button onClick={()=>void close()}><LockKeyhole/>Генерирай пакет и заключи</Button>{data?.closures.map(c=><div className="closure-row" key={c.id}><span><strong>{c.period}</strong><small>{formatDateTime(c.closed_at)}</small></span>{c.has_package?<Button size="sm" variant="outline" title={`Изтегли архивния счетоводен пакет за ${c.period}`} onClick={()=>void downloadAccounting(token,`/admin/accounting/closures/${c.id}/download`,`accounting-${c.period}.zip`)}><Download/>ZIP</Button>:null}</div>)}</section><section className="accounting-panel"><SectionTitle title="Audit log" help="Неизменяем журнал на важните счетоводни действия: платежни операции, Econt сверяване, документи, промени по поръчки и приключване на период."/><div className="audit-list">{data?.audit_log.map(log=><div key={log.id}><span><strong>{actionLabels[log.action]??log.action}</strong><small>{log.entity_type}{log.entity_id?` #${log.entity_id}`:''}</small></span><time>{formatDateTime(log.created_at)}</time></div>)}{data?.audit_log.length===0?<p>Все още няма счетоводни промени.</p>:null}</div></section></div>
 </div>;
}
function Metric({label,value,help,icon}:{label:string;value:string;help:string;icon?:ReactNode}){return <article>{icon}<span className="accounting-metric-label">{label}<HelpHint label={label}>{help}</HelpHint></span><strong>{value}</strong></article>}
function SectionTitle({title,help,icon}:{title:string;help:string;icon?:ReactNode}){return <div className="accounting-section-title">{icon}<h2>{title}</h2><HelpHint label={title}>{help}</HelpHint></div>}
