server {
    listen 80;
    server_name _;
    root /var/www/plans/public;
    index index.php;

    client_max_body_size 40M;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }
}

server {
    listen 8080;
    server_name _;
    root /var/www/api/public;
    index index.php;

    client_max_body_size 40M;

    location ^~ /uploads/ {
        location ~* \.(php|phtml|phar)$ {
            deny all;
        }

        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_index index.php;
    }
}
