import Alpine from 'alpinejs';
import { registerStoreAvatar } from './avatar.js';
import { registerStoreForm } from './form.js';
import { registerStoreHeader } from './nav.js';
import { mountProductReviews, registerStoreProduct } from './product.js';
import { mountStoreCart } from './cart.js';
import { mountCartPage } from './cart-page.js';
import { registerStoreFavorites } from './favorites.js';
import { mountStoreToasts } from './toast.js';
import { registerThemeStore } from './theme.js';
import { registerTooltip } from './tooltip.js';
import { mountCatalogGrid } from './catalog.js';
import { mountStoreCheckout } from './checkout.js';
import { mountAccountMessages } from './account-messages.js';
import { mountFreeShippingNotice } from './free-shipping-notice.js';
import './app.css';

window.Alpine = Alpine;
registerThemeStore(Alpine);
registerStoreHeader(Alpine);
registerStoreAvatar(Alpine);
registerStoreForm(Alpine);
registerStoreProduct(Alpine);
registerTooltip(Alpine);
Alpine.start();
mountStoreToasts();
mountStoreCart();
mountCartPage();
registerStoreFavorites();
mountCatalogGrid();
mountStoreCheckout();
mountAccountMessages();
mountFreeShippingNotice();
mountProductReviews();
