<script setup>
import { reactive, ref } from 'vue';
import StoreButton from './StoreButton.vue';
const props = defineProps({ config: { type: Object, required: true } });
const step = ref(props.config.step === 'device' ? 'device' : 'credentials');
const busy = ref(null);
const loginMessage = ref(props.config.login?.message || ''); const loginIsError = ref(Boolean(props.config.login?.isError));
const registerMessage = ref(props.config.register?.message || ''); const registerIsError = ref(Boolean(props.config.register?.isError));
const normalize = (raw) => Object.fromEntries(Object.entries(raw || {}).map(([key, value]) => [key, Array.isArray(value) ? String(value[0] || '') : String(value || '')]));
const loginErrors = ref(normalize(props.config.login?.errors)); const registerErrors = ref(normalize(props.config.register?.errors));
const show = reactive({ login: false, register: false, confirm: false });
const login = reactive({ email: props.config.login?.email || '', password: '', code: '' });
const initial = props.config.register?.fields || {};
const register = reactive({ first_name: initial.first_name || '', last_name: initial.last_name || '', email: initial.email || '', phone: initial.phone || '', password: '', password_confirmation: '' });
function data(values) { const form = new FormData(); form.set('_token', props.config.csrf || ''); Object.entries(values).forEach(([key, value]) => form.set(key, String(value ?? ''))); if (props.config.returnTo) form.set('return', props.config.returnTo); return form; }
async function request(url, values) { const response = await fetch(url, { method: 'POST', headers: { Accept: 'application/json' }, body: data(values) }); const payload = await response.json().catch(() => null); if (!response.ok) { const error = new Error(payload?.message || 'Заявката не беше успешна.'); error.errors = normalize(payload?.errors); throw error; } return payload; }
async function submitLogin() { busy.value = 'login'; loginErrors.value = {}; loginMessage.value = ''; loginIsError.value = false; try { const payload = await request('/login', { ...login, step: step.value }); if (payload?.data?.requires_device_verification) { step.value = 'device'; login.email = payload.data.email || login.email; login.password = ''; loginMessage.value = payload.message || 'Изпратихме код на имейла Ви.'; return; } window.location.assign(payload?.data?.redirect || '/account'); } catch (error) { loginErrors.value = error.errors || {}; loginMessage.value = error.message; loginIsError.value = true; } finally { busy.value = null; } }
async function submitRegister() { busy.value = 'register'; registerErrors.value = {}; registerMessage.value = ''; registerIsError.value = false; try { const payload = await request('/register', register); window.location.assign(payload?.data?.redirect || '/account/profile'); } catch (error) { registerErrors.value = error.errors || {}; registerMessage.value = error.message; registerIsError.value = true; } finally { busy.value = null; } }
async function resend() { busy.value = 'resend'; loginMessage.value = ''; loginIsError.value = false; try { const payload = await request('/login/code', { email: login.email }); loginMessage.value = payload?.message || 'Изпратихме нов код.'; } catch (error) { loginMessage.value = error.message; loginIsError.value = true; } finally { busy.value = null; } }
</script>
<template>
<section class="store-auth" :class="{ 'store-auth--device': step === 'device' }">
  <div class="store-auth-column"><h1>{{ step === 'device' ? 'Потвърдете устройството' : 'Вход' }}</h1><p class="store-auth-lead">{{ step === 'device' ? 'Въведете 6-цифрения код, който изпратихме на имейла Ви.' : 'Влезте, за да управлявате профила, поръчките и любимите си продукти.' }}</p><p v-if="loginMessage" class="store-auth-message" :class="{ 'is-error': loginIsError }" role="status">{{ loginMessage }}</p>
    <form class="store-auth-form" novalidate @submit.prevent="submitLogin">
      <template v-if="step === 'credentials'"><label>Имейл<input v-model="login.email" type="email" autocomplete="username" required><small v-if="loginErrors.email">{{ loginErrors.email }}</small></label><label>Парола<span class="store-auth-password"><input v-model="login.password" :type="show.login ? 'text' : 'password'" autocomplete="current-password" required><button type="button" @click="show.login = !show.login">{{ show.login ? 'Скрий' : 'Покажи' }}</button></span><small v-if="loginErrors.password">{{ loginErrors.password }}</small></label></template>
      <template v-else><label>Код<input v-model="login.code" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="6" required><small v-if="loginErrors.code">{{ loginErrors.code }}</small></label></template>
      <StoreButton type="submit" :busy="busy === 'login'" :disabled="busy !== null" :label="step === 'device' ? 'Потвърди' : 'Вход'" busy-label="Влизане…" />
    </form><template v-if="step === 'device'"><StoreButton class="mt-3" :busy="busy === 'resend'" :disabled="busy !== null" label="Изпрати нов код" busy-label="Изпращане…" @click="resend"/><button type="button" class="store-auth-back" @click="step = 'credentials'; login.code = ''; loginMessage = ''">Назад към входа</button></template>
  </div>
  <div v-if="step !== 'device'" class="store-auth-column store-auth-register"><h2>Регистрация</h2><p class="store-auth-lead">Създайте профил, за да пазите любими продукти, поръчки и настройки.</p><p v-if="registerMessage" class="store-auth-message" :class="{ 'is-error': registerIsError }" role="status">{{ registerMessage }}</p>
    <form class="store-auth-form" novalidate @submit.prevent="submitRegister"><div class="store-auth-row"><label>Име<input v-model="register.first_name" autocomplete="given-name" required><small v-if="registerErrors.first_name">{{ registerErrors.first_name }}</small></label><label>Фамилия<input v-model="register.last_name" autocomplete="family-name" required><small v-if="registerErrors.last_name">{{ registerErrors.last_name }}</small></label></div><label>Имейл<input v-model="register.email" type="email" autocomplete="email" required><small v-if="registerErrors.email">{{ registerErrors.email }}</small></label><label>Телефон <span class="store-auth-optional">(по желание)</span><input v-model="register.phone" type="tel" autocomplete="tel"><small v-if="registerErrors.phone">{{ registerErrors.phone }}</small></label><label>Парола<span class="store-auth-password"><input v-model="register.password" :type="show.register ? 'text' : 'password'" autocomplete="new-password" required><button type="button" @click="show.register = !show.register">{{ show.register ? 'Скрий' : 'Покажи' }}</button></span><small v-if="registerErrors.password">{{ registerErrors.password }}</small></label><label>Потвърдете паролата<span class="store-auth-password"><input v-model="register.password_confirmation" :type="show.confirm ? 'text' : 'password'" autocomplete="new-password" required><button type="button" @click="show.confirm = !show.confirm">{{ show.confirm ? 'Скрий' : 'Покажи' }}</button></span><small v-if="registerErrors.password_confirmation">{{ registerErrors.password_confirmation }}</small></label><StoreButton type="submit" :busy="busy === 'register'" :disabled="busy !== null" label="Създай профил" busy-label="Създаване…" /></form>
  </div>
</section>
</template>
